### ISSUE TITLE
Why do descriptions have key?

### ISSUE THREAD

**Issue by peterdesmet** [gbif/gbif-api#32]
When querying for species related information, I expect the `taxonKey` to be the first attribute. This is true for all except `descriptions`:

- [distributions](http://api.gbif.org/v1/species/140562891/distributions): `taxonKey`
- [speciesProfiles](http://api.gbif.org/v1/species/140562891/speciesProfiles): `taxonKey`
- [descriptions](http://api.gbif.org/v1/species/140562891/descriptions): `key`, then `taxonKey`

Why do descriptions have their own key?

**Comment by mdoering** [comment]
In order to load them individually. The previous GBIF portal made use of that when we first showed a Table of Content with just the subjects & languages and then loaded individual descriptions.

As its there already, we cant remove it without breaking the API contract. Though I doubt this would hurt anyone in reality.

**Comment by peterdesmet** [comment]
Thanks, good to know. No issue that they are there.
