### ISSUE TITLE
occurrenceStatus missing in API species distribution enpoint

### ISSUE THREAD

**Issue by damianooldoni** [gbif/gbif-api#94]
Hi,

Can it be that since a few days `occurrenceStatus` is missing in API species distribution endpoint for taxa with one distribution only? For taxa with multiple distributions, `occurrenceStatus` is still present in information retrieved via API.

On website I can see the field `occurrenceStatus` in Species Distribution (https://www.gbif.org/species/140563025/verbatim)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/33662631/178978692-e67cc2f5-70ba-4f9d-a906-c108f28fb6e7.png">

However, this information is not present while retrieving distribution from API (https://api.gbif.org/v1/species/140563025/distributions):
```json
{
"offset": 0,
"limit": 20,
"endOfRecords": true,
"results": [
{
"taxonKey": 140563025,
"locationId": "ISO_3166-2:BE-VLG",
"locality": "Flemish Region",
"country": "BE",
"temporal": "2007/2016",
"establishmentMeans": "INTRODUCED",
"source": "van Haaren T, Soors J (2009) Sinelobus stanfordi (Richardson, 1901): a new crustacean invader in Europe. Aquatic Invasions 4: 703–711, https://doi.org/10.3391/ai.2009.4.4.20"
}
]
}
```

This doesn't happen when multiple distributions are present. Example: website (https://www.gbif.org/species/141265335/verbatim) and API (https://api.gbif.org/v1/species/141265335/distributions).

**Comment by damianooldoni** [comment]
Update: now `occurrenceStatus` is missing from data retrieved via API when multiple distributions are present as well. Check the same example as above:
website (https://www.gbif.org/species/141265335/verbatim) vs API (https://api.gbif.org/v1/species/141265335/distributions).

Any idea when this can be fixed? Thanks in advance.

**Comment by mdoering** [comment]
This looks indeed like a bug. There should be a controlled `status` field for each distribution.
We have changed the vocabulary for the occurrence status to a new [DistributionStatus](https://github.com/gbif/gbif-api/blame/dev/src/main/java/org/gbif/api/vocabulary/DistributionStatus.java) enumeration - perhaps that is the cause of the problem. The enumeration was introduced into the API classes 3 years ago, but we only put that live into the production species API sometime in April last year. So that corresponds to your initial issue date.

**Comment by mdoering** [comment]
deployed and reinterpreted.

**Comment by damianooldoni** [comment]
Hi @mdoering, issue solved on prod for multiple species distributions. But occurrenceStatus is still missing for taxa with one species distribution. See https://api.gbif.org/v1/species/140563025/distributions
